
-- Production Order
CREATE TABLE IF NOT EXISTS TBL_PRODUCTION_ORDER (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ORDER_NUMBER VARCHAR(100) NOT NULL,
    ORDER_NAME VARCHAR(255),
    DESCRIPTION TEXT NULL,
    QUANTITY INT NOT NULL,
    ORDER_TYPE VARCHAR(50) NOT NULL,
    STATUS VARCHAR(50) DEFAULT 'PENDING',
    IS_ACTIVE BOOLEAN DEFAULT TRUE ,
    CREATED_BY BIGINT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY BIGINT NULL,
    MODIFIED_DATE TIMESTAMP NULL
);

-- Machine
CREATE TABLE IF NOT EXISTS TBL_MACHINE (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    TYPE VARCHAR(100),
    STATUS VARCHAR(50),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY BIGINT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY BIGINT NULL,
    MODIFIED_DATE TIMESTAMP NULL
);

-- Machine Order
CREATE TABLE IF NOT EXISTS TBL_MACHINE_ORDER (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRODUCTION_ORDER_ID BIGINT REFERENCES TBL_PRODUCTION_ORDER(ID),
    MACHINE_ID BIGINT REFERENCES TBL_MACHINE(ID),
    QUANTITY INT,
    STATUS VARCHAR(50),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY BIGINT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY BIGINT NULL,
    MODIFIED_DATE TIMESTAMP NULL
);

---- Machine Event
--CREATE TABLE IF NOT EXISTS TBL_MACHINE_EVENT (
--    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--    MACHINE_ORDER_ID BIGINT REFERENCES TBL_MACHINE_ORDER(ID),
--    EVENT_TYPE VARCHAR(50),
--    DESCRIPTION VARCHAR(500),
--    TIMESTAMP TIMESTAMP,
--    IS_ACTIVE BOOLEAN DEFAULT TRUE,
--    CREATED_BY BIGINT NULL,
--    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    MODIFIED_BY BIGINT NULL,
--    MODIFIED_DATE TIMESTAMP NULL
--);